baseURL = "http://shehio.com/"
languageCode = "en-us"
title = "Shehio"
theme = "ananke"

[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.primary]]
    name = "GitHub"
    url = "https://github.com/shehio"
    weight = 3
[[menu.primary]]
    name = "Twitter"
    url = "https://twitter.com/shehabyasser"
    weight = 4
