baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-tanka"

[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.primary]]
    name = "GitHub"
    url = "https://github.com/shehio"
    weight = 3
[[menu.primary]]
    name = "Twitter"
    url = "https://twitter.com/shehabyasser"
    weight = 4
